### ISSUE TITLE
setparam.hoc error after running openmodel.hoc

### ISSUE THREAD

**Issue by Dauriel** [ModelDBRepository/260967#1]
Hi!

I'm having an issue with the setparam.hoc file. I download the model and compile mod files but once I run openmodel.hoc it crashes.

Here's the error log:

> C:\nrn\bin\nrniv.exe: na is not a MECHANISM
>  in setparam.hoc near line 424
>                 insert na
>            ^
>         xopen("setparam.hoc")
>       execute1("{xopen("se...")
>     load_file("setparam.hoc")
>   xopen("openmodel.hoc")
> and others
>         0
> C:\nrn\bin\nrniv.exe: setions undefined function
>  in setparam.hoc near line 66
>  setparam()
>            ^
>         setions()
>       setparam()
>     xopen("openmodel.hoc")
>   execute1("{xopen("op...")
> and others
>         0

**Comment by ramcdougal** [comment]
How are you compiling the mod files... From the directory with the HOC code, I'd run

```
nrnivmodl lib
```

(Note that you need the `lib` since that's where the mod files are; they're not in the same directory as the code)

**Comment by Dauriel** [comment]
Thanks! (I was building the .dll from the lib folder... in the lib folder, sorry for that)
